name: 🚀

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Build
        run: |
          corepack enable
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm build
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - name: Copy template
        run: |
          pnpm copy:collection
          pnpm copy:template
      - name: Release
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          NODE_AUTH_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
